### ISSUE TITLE
Light client related types are out dated after Shapella upgrade

### ISSUE THREAD

**Issue by patrickmao93** [umbracle/go-eth-consensus#36]
the `AttestedHeader` and `FinalizedHeader` fields in `LightClientFinalityUpdate`, `LightClientOptimisticUpdate`, and `LightClientUpdate` have another wrapper struct around them, i.e.:

```
type Header struct {
    Beacon BeaconBlockHeader `json:"beacon"`
    Execution ExecutionPayloadHeader `json:"execution"`
    ExecutionBranch [][32]byte `json:"execution_branch"`
}
```

**Comment by ferranbt** [comment]
Hey, sorry for the delay, somehow I do not get notified on this repo. Can you point me out to the new types in the consensus spec?

**Comment by ferranbt** [comment]
Do you mean these containers from `Altair`?
```
class LightClientHeader(Container):
    # Beacon block header
    beacon: BeaconBlockHeader

class LightClientUpdate(Container):
    # Header attested to by the sync committee
    attested_header: LightClientHeader
```

**Comment by ferranbt** [comment]
I see, let me check and get back to you, it should not be hard to integrate.

**Comment by ferranbt** [comment]
So, `go-eth-consensus` uses the official spec tests SSZ encoding to make sure the type (and the encoding) of every consensus type is correct.

In those spec tests, the light client types for the `capella` fork do not have the modified `LightClientHeader`, that is why the SSZ unit tests work locally without any changes.

Maybe this should be raised first there to see if there is any error because if I change the types on this side, I will have to disable some of the tests.

**Comment by ferranbt** [comment]
The issue was that the repo was using an old version of the spec tests that did not have the correct version of the light client types. When I created the types initially, I used as a reference the tests instead of the spec.
